version: '3.6'

services:
   kafka:
     image: spotify/kafka
     container_name: hd_kafka
     ports:
         - 2181:2181
         - 9092:9092
     environment:
         ADVERTISED_PORT: 9092
         ADVERTISED_HOST: ${DOCKER_HOST_IP}  # For accessing kafka queue from localhost
     restart: always

   app:
     build:
        context: ./app
     image: app:0.0.1
     container_name: hd_app
     restart: always
     depends_on:
      - "kafka"
      - "spider"
      - "redis"
      - "es"
     healthcheck:
        test: ["CMD", "curl", "-f", "http://app:8000"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
     ports:
       - 80:8000

   reviewer:
     build:
        context: ./reviewer
     image: reviewer:0.0.1
     container_name: hd_reviewer
     restart: always
     depends_on:
      - "kafka"
      - "es"
      - "redis"

   spider:
     build:
        context: ./spider
     image: spider:0.0.1
     container_name: hd_spider
     depends_on:
      - "reviewer"
      - "kafka"
      - "es"
     restart: always

   redis:
     image: redis:latest
     container_name: hd_redis
     restart: always

   es:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
     container_name: hd_es
     restart: always
     ports:
       - 9200:9200
       - 9300:9300
     environment:
         - discovery.type=single-node
