version: '2.2'

services:
  es:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
     container_name: hd_es
     restart: always
     ports:
       - 9200:9200
       - 9300:9300
     environment:
        - discovery.type=single-node

  # docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.5.0
